---
# Follow the OT-Settings repo to complete the config.sh file
# Execute this playbook with the following:
# cd ~/OT-DockSucker
# ansible-playbook -u root -k -i /etc/ansible/hostsCONVERT ansible/convert-to-docksucker.yml

- name: Convert existing nodes to DockSucker
  hosts: all
  gather_facts: yes

  tasks:
  - name: Set hostname
    hostname:
      name: '{{node_name}}'

  - name: Make /root directory
    file:
      path: /root
      state: directory
      mode: '0770'

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Clone OT-DockSucker git repository
    git:
      repo: 'https://github.com/calr0x/OT-DockSucker.git'
      dest: /root/OT-DockSucker
      force: yes

  - name: Clone OT-Settings git repository
    git:
      repo: 'https://github.com/calr0x/OT-Settings.git'
      dest: /root/OT-Settings
      force: yes

  - name: Copy config file
    copy:
      src: ~/OT-Settings/config.sh
      dest: /root/OT-Settings
      owner: root
      group: root
      mode: '0700'
  
  - name: Execute DockSucker installation
    shell: /root/OT-DockSucker/install-from-existing.sh >> OUTPUT
    args:
      chdir: /root/OT-DockSucker/
